[variables]
    PYTHONPATH = "/app/backend"
    PORT = "8000"

[phases.setup]
    nixPkgs = ["python39", "pip"]

[phases.install]
    cmds = ["pip install -r requirements.txt"]

[phases.build]
    cmds = ["echo 'Build complete'"]

[start]
    cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT" 