[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

# Railway の監視設定
[monitoring]
healthcheck = true

# ビルド除外設定
[build.ignore]
paths = ["frontend/", ".github/", "*.md", ".git/", "ai_service/"] 