[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

# 自動デプロイ設定
[env]
PORT = "8000"

# Railway の監視設定
[monitoring]
healthcheck = true

# ビルド除外設定
[build.ignore]
paths = ["frontend/", ".github/", "*.md", ".git/"] 