services:
  # バックエンドAPI（FastAPI + AI統合）
  - type: web
    name: daily-stock-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: ./backend
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: FRONTEND_URL
        value: https://daily-stock.netlify.app
    
  # データベース（PostgreSQL）
databases:
  - name: daily-stock-db
    databaseName: daily_stock
    user: daily_stock_user 